### ISSUE TITLE
Entering garbage symbols causes error to be thrown

### ISSUE THREAD

**Issue by CExJBoudreau** [adamwdraper/Numeral-js#317]
How to reproduce:

``` javascript
numeral('%^.&*').format('0.0')
```

Result:

```
/Users/jboudreau/workspaces/my_project/node_modules/numeral/numeral.js:360
                if (d.split('.')[1].length) {
                                   ^
TypeError: Cannot read property 'length' of undefined
    at formatNumber (/Users/jboudreau/workspaces/config_ucps_v5/node_modules/numeral/numeral.js:360:36)
    at formatNumeral (/Users/jboudreau/workspaces/config_ucps_v5/node_modules/numeral/numeral.js:75:22)
    at Object.numeral.fn.Numeral.format (/Users/jboudreau/workspaces/config_ucps_v5/node_modules/numeral/numeral.js:587:20)
    at Object.<anonymous> (/Users/jboudreau/workspaces/config_ucps_v5/num.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Expected result: `"0.0"`.

**Comment by adamwdraper** [comment]
Done!
